name: remind_dev
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.0
  shared_preferences: ^2.0.15
  flutter_colorpicker: ^1.0.3
  intl: 0.19.0
  provider: ^6.0.0
  flutter_blue_plus: ^1.32.12 
    #path: '../flutter_blue_plus'
  firebase_core: ^3.2.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  geolocator: ^12.0.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+2
  sign_in_button: ^3.2.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true